require 'csv'
require 'set'

module Countries
  def country_get_one_field(record, fields)
    fields.map  { |field| record[field.to_sym] }.reject { |val| val.nil? }[0]
  end

  def country_fix_record(record)
    @seen_before ||= Set.new
    ret = {}
    begin

      ret[:province] = country_get_one_field(record, ['Province/State', 'Province_State'])
      c = country_get_one_field(record, ['Country/Region', 'Country_Region'])
      c = 'United States' if c == 'US'
      c = 'Cruise Ship' if c.downcase == 'others' && ret[:province].downcase.match('ship')
      c = 'Cruise Ship' if c == 'MS Zaandam'
      ret[:country], ret[:code] = country_to_code(c)

      d = country_get_one_field(record, ['Last Update', 'Last_Update']).gsub(' ', 'T').split('T')[0].strip
      d = if d.match(/^(\d{4})-(\d{2})-(\d{2})$/)
            d
          elsif d.match(/^(\d+)\/(\d+)\/(\d+)$/)
            m, d, y = d.split('/').map { |v| v.to_i}
            y += 2000 if y < 2000
            '%04d-%02d-%02d' % [y, m, d]
          else
            puts "Bad d: '#{d}'"
          end
      ret[:date] = d
      ret[:cases] = record[:Confirmed]
      ret[:deaths] = record[:Deaths]
      ret[:recovered] = record[:Recovered]
      ret[:population] = country_population(ret[:country])

      return if c == 'Italy' && %w[2020-01-31 2020-02-07].include?(d)

      rd = Marshal.dump(ret.values)
      return if @seen_before.include?(rd)
      @seen_before << rd
      if ret[:country] == 'Italy' && ret[:date] == '2020-02-07'
        pp @seen_before.select { |r| r.match('2020-02-07') && r.match('Italy')}.length
        pp @seen_before.length
        pp ret.values
      end
    rescue Exception => e
      puts __method__
      puts "Bad parsing in fix_country"
      pp record
      puts e.message
      puts e.backtrace
      exit
    end
    ret
  end

  def country_to_code(country)
    {
      # Special ones
      'United States' => ['United States','USA'],
      'USA' => ['United States','USA'],
      'Mainland China' => ['China','CHN'],
      'United Kingdom' => ['United Kingdom','GBR'],
      'UK' => ['United Kingdom', 'GBR'],
      'Korea, South' => ['South Korea','KOR'],
      'South Korea' => ['South Korea','KOR'],
      'Italy' => ['Italy','ITA'],

      # split out cruise ships
      'Others' => ['Others', "OTH"],
      'Diamond Princess' => ['Cruise Ships','CSS'],
      'Cruise Ship' =>  ['Cruise Ships','CSS'],

      'Afghanistan' => ['Afghanistan', 'AFG'],
      'Aland Islands' => ['Aland Islands','ALA'],
      'Albania' => ['Albania', 'ALB'],
      'Algeria' => ['Algeria', 'DZA'],
      'American Samoa' => ['American Samoa', 'ASM'],
      'Andorra' => ['Andorra', 'AND'],
      'Angola' => ['Angola', 'AGO'],
      'Anguilla' => ['Anguilla', 'AIA'],
      'Antarctica' => ['Antarctica', 'ATA'],
      'Antigua and Barbuda' => ['Antigua and Barbuda', 'ATG'],
      'Argentina' => ['Argentina', 'ARG'],
      'Armenia' => ['Armenia', 'ARM'],
      'Aruba' => ['Aruba', 'ABW'],
      'Australia' => ['Australia', 'AUS'],
      'Austria' => ['Austria', 'AUT'],
      'Azerbaijan' => ['Azerbaijan','AZE'],
      'Bahamas (the)' => ['Bahamas', 'BHS'],
      'Bahamas, The' => ['Bahamas', 'BHS'],
      'Bahamas' => ['Bahamas', 'BHS'],
      'Bahrain' => ['Bahrain', 'BHR'],
      'Bangladesh' => ['Bangladesh', 'BGD'],
      'Barbados' => ['Barbados', 'BRB'],
      'Belarus' => ['Belarus', 'BLR'],
      'Belgium' => ['Belgium', 'BEL'],
      'Belize' => ['Belize', 'BLZ'],
      'Benin' => ['Benin', 'BEN'],
      'Bermuda' => ['Bermuda', 'BMU'],
      'Bhutan' => ['Bhutan', 'BTN'],
      'Bolivia (Plurinational State of)' => ['Bolivia', 'BOL'],
      'Bolivia' => ['Bolivia', 'BOL'],
      'Bonaire, Sint Eustatius and Saba' => ['Bonaire, Sint Eustatius and Saba', 'BES'],
      'Bosnia and Herzegovina' => ['Bosnia and Herzegovina', 'BIH'],
      'Botswana' => ['Botswana', 'BWA'],
      'Bouvet Island' => ['Bouvet Island', 'BVT'],
      'Brazil' => ['Brazil', 'BRA'],
      'British Indian Ocean Territory (the)' => ['British Indian Ocean Territory', 'IOT'],
      'Brunei Darussalam' => ['Brunei Darussalam', 'BRN'],
      'Brunei' => ['Brunei', 'BRN'],
      'Bulgaria' => ['Bulgaria', 'BGR'],
      'Burkina Faso' => ['Burkina Faso', 'BFA'],
      'Burma' => ['Burma', ''],
      'Burundi' => ['Burundi', 'BDI'],
      'Cabo Verde' => ['Cabo Verde', 'CPV'],
      'Cambodia' => ['Cambodia', 'KHM'],
      'Cameroon' => ['Cameroon', 'CMR'],
      'Canada' => ['Canada', 'CAN'],
      'Cape Verde' => ['Cape Verde', ''],
      'Cayman Islands (the)' => ['Cayman Islands', 'CYM'],
      'Cayman Islands' => ['Cayman Islands', ''],
      'Central African Republic (the)' => ['Central African Republic', 'CAF'],
      'Central African Republic' => ['Central African Republic', 'CAF'],
      'Chad' => ['Chad', 'TCD'],
      'Channel Islands' => ['Channel Islands', ''],
      'Chile' => ['Chile', 'CHL'],
      'China' => ['China', 'CHN'],
      'Christmas Island' => ['Christmas Island', 'CXR'],
      'Cocos (Keeling) Islands (the)' => ['Cocos Islands', 'CCK'],
      'Colombia' => ['Colombia', 'COL'],
      'Comoros (the)' => ['Comoros', 'COM'],
      'Congo (Brazzaville)' => ['Congo', 'COD'],
      'Congo (Kinshasa)' => ['Congo', 'COD'],
      'Congo (the Democratic Republic of the)' => ['Congo', 'COD'],
      'Congo (the)' => ['Congo', 'COG'],
      'Cook Islands (the)' => ['Cook Islands', 'COK'],
      'Costa Rica' => ['Costa Rica', 'CRI'],
      'Cote d\'Ivoire' => ['Ivory Coast', 'CIV'],
      'Croatia' => ['Croatia', 'HRV'],
      'Cuba' => ['Cuba', 'CUB'],
      'Curacao' => ['Curacao', ''],
      'Curaçao' => ['Curacao', 'CUW'],
      'Cyprus' => ['Cyprus', 'CYP'],
      'Czech Republic' => ['Czech Republic', ''],
      'Czechia' => ['Czechia', 'CZE'],
      'Denmark' => ['Denmark', 'DNK'],
      'Djibouti' => ['Djibouti', 'DJI'],
      'Dominica' => ['Dominica', 'DMA'],
      'Dominican Republic (the)' => ['Dominican Republic', 'DOM'],
      'Dominican Republic' => ['Dominican Republic', ''],
      'East Timor' => ['East Timor', ''],
      'Ecuador' => ['Ecuador', 'ECU'],
      'Egypt' => ['Egypt', 'EGY'],
      'El Salvador' => ['El Salvador', 'SLV'],
      'Equatorial Guinea' => ['Equatorial Guinea', 'GNQ'],
      'Eritrea' => ['Eritrea', 'ERI'],
      'Estonia' => ['Estonia', 'EST'],
      'Eswatini' => ['Eswatini', 'SWZ'],
      'Ethiopia' => ['Ethiopia', 'ETH'],
      'Falkland Islands (the) [Malvinas]' => ['Falkland Islands', 'FLK'],
      'Faroe Islands (the)' => ['Faroe Islands', 'FRO'],
      'Faroe Islands' => ['Faroe Islands', ''],
      'Fiji' => ['Fiji', 'FJI'],
      'Finland' => ['Finland', 'FIN'],
      'France' => ['France', 'FRA'],
      'French Guiana' => ['French Guiana', 'GUF'],
      'French Polynesia' => ['French Polynesia', 'PYF'],
      'French Southern Territories (the)' => ['French Southern Territories', 'ATF'],
      'Gabon' => ['Gabon', 'GAB'],
      'Gambia (the)' => ['Gambia', 'GMB'],
      'Gambia, The' => ['Gambia', ''],
      'Gambia' => ['Gambia', ''],
      'Georgia' => ['Georgia', 'GEO'],
      'Germany' => ['Germany', 'DEU'],
      'Ghana' => ['Ghana', 'GHA'],
      'Gibraltar' => ['Gibraltar', 'GIB'],
      'Greece' => ['Greece', 'GRC'],
      'Greenland' => ['Greenland', 'GRL'],
      'Grenada' => ['Grenada', 'GRD'],
      'Guadeloupe' => ['Guadeloupe', 'GLP'],
      'Guam' => ['Guam', 'GUM'],
      'Guatemala' => ['Guatemala', 'GTM'],
      'Guernsey' => ['United Kingdom', 'GRB'],
      'Guinea-Bissau' => ['Guinea-Bissau', 'GNB'],
      'Guinea' => ['Guinea', 'GIN'],
      'Guyana' => ['Guyana', 'GUY'],
      'Haiti' => ['Haiti', 'HTI'],
      'Heard Island and McDonald Islands' => ['Heard Island and McDonald Islands', 'HMD'],
      'Holy See (the)' => ['Vatican', 'VAT'],
      'Holy See' => ['Vatican', 'VAT'],
      'Honduras' => ['Honduras', 'HND'],
      'Hong Kong SAR' => ['Hong Kong', 'HKG'],
      'Hong Kong' => ['Hong Kong', 'HKG'],
      'Hungary' => ['Hungary', 'HUN'],
      'Iceland' => ['Iceland', 'ISL'],
      'India' => ['India', 'IND'],
      'Indonesia' => ['Indonesia', 'IDN'],
      'Iran (Islamic Republic of)' => ['Iran', 'IRN'],
      'Iraq' => ['Iraq', 'IRQ'],
      'Ireland' => ['Ireland', 'IRL'],
      'Isle of Man' => ['Isle of Man', 'IMN'],
      'Israel' => ['Israel', 'ISR'],
      'Ivory Coast' => ['Ivory Coast', ''],
      'Jamaica' => ['Jamaica', 'JAM'],
      'Japan' => ['Japan', 'JPN'],
      'Jersey' => ['United Kingdom', 'GRB'],
      'Jordan' => ['Jordan', 'JOR'],
      'Kazakhstan' => ['Kazakhstan', 'KAZ'],
      'Kenya' => ['Kenya', 'KEN'],
      'Kiribati' => ['Kiribati', 'KIR'],
      'Korea (the Republic of)' => ['Korea', 'KOR'],
      'Kosovo' => ['Kosovo', ''],
      'Kuwait' => ['Kuwait', 'KWT'],
      'Kyrgyzstan' => ['Kyrgyzstan', 'KGZ'],
      'Laos' => ['Laos', ''],
      'Latvia' => ['Latvia', 'LVA'],
      'Lebanon' => ['Lebanon', 'LBN'],
      'Lesotho' => ['Lesotho', 'LSO'],
      'Liberia' => ['Liberia', 'LBR'],
      'Libya' => ['Libya', 'LBY'],
      'Liechtenstein' => ['Liechtenstein', 'LIE'],
      'Lithuania' => ['Lithuania', 'LTU'],
      'Luxembourg' => ['Luxembourg', 'LUX'],
      'Macao SAR' => ['Macao', ''],
      'Macao' => ['Macao', 'MAC'],
      'Macau' => ['Macau', 'MAC'],
      'Madagascar' => ['Madagascar', 'MDG'],
      'Malawi' => ['Malawi', 'MWI'],
      'Malaysia' => ['Malaysia', 'MYS'],
      'Maldives' => ['Maldives', 'MDV'],
      'Mali' => ['Mali', 'MLI'],
      'Malta' => ['Malta', 'MLT'],
      'Marshall Islands (the)' => ['Marshall Islands', 'MHL'],
      'Martinique' => ['Martinique', 'MTQ'],
      'Mauritania' => ['Mauritania', 'MRT'],
      'Mauritius' => ['Mauritius', 'MUS'],
      'Mayotte' => ['Mayotte', 'MYT'],
      'Mexico' => ['Mexico', 'MEX'],
      'Micronesia (Federated States of)' => ['Micronesia', 'FSM'],
      'Moldova (the Republic of)' => ['Moldova', 'MDA'],
      'Moldova' => ['Moldova', ''],
      'Monaco' => ['Monaco', 'MCO'],
      'Mongolia' => ['Mongolia', 'MNG'],
      'Montenegro' => ['Montenegro', 'MNE'],
      'Montserrat' => ['Montserrat', 'MSR'],
      'Morocco' => ['Morocco', 'MAR'],
      'Mozambique' => ['Mozambique', 'MOZ'],
      'MS Zaandam' => ['MS Zaandam', ''],
      'Myanmar' => ['Myanmar', 'MMR'],
      'Namibia' => ['Namibia', 'NAM'],
      'Nauru' => ['Nauru', 'NRU'],
      'Nepal' => ['Nepal', 'NPL'],
      'Netherlands (the)' => ['Netherlands', 'NLD'],
      'Netherlands' => ['Netherlands', 'NLD'],
      'New Caledonia' => ['New Caledonia', 'NCL'],
      'New Zealand' => ['New Zealand', 'NZL'],
      'Nicaragua' => ['Nicaragua', 'NIC'],
      'Niger (the)' => ['Niger (the)', 'NER'],
      'Niger' => ['Niger', ''],
      'Nigeria' => ['Nigeria', 'NGA'],
      'Niue' => ['Niue', 'NIU'],
      'Norfolk Island' => ['Norfolk Island', 'NFK'],
      'North Ireland' => ['United Kingdom', 'GRB'],
      'North Macedonia' => ['North Macedonia', 'MKD'],
      'Northern Mariana Islands (the)' => ['Northern Mariana Islands', 'MNP'],
      'Norway' => ['Norway', 'NOR'],
      'occupied Palestinian territory' => ['Palestine', ''],
      'Oman' => ['Oman', 'OMN'],
      'Pakistan' => ['Pakistan', 'PAK'],
      'Palau' => ['Palau', 'PLW'],
      'Palestine, State of' => ['Palestine', 'PSE'],
      'Palestine' => ['Palestine', ''],
      'Panama' => ['Panama', 'PAN'],
      'Papua New Guinea' => ['Papua New Guinea', 'PNG'],
      'Paraguay' => ['Paraguay', 'PRY'],
      'Peru' => ['Peru', 'PER'],
      'Philippines (the)' => ['Philippines', 'PHL'],
      'Philippines' => ['Philippines', 'PHL'],
      'Pitcairn' => ['Pitcairn', 'PCN'],
      'Poland' => ['Poland', 'POL'],
      'Portugal' => ['Portugal', 'PRT'],
      'Puerto Rico' => ['Puerto Rico', 'PRI'],
      'Qatar' => ['Qatar', 'QAT'],
      'Republic of Ireland' => ['Ireland', ''],
      'Republic of Korea' => ['South Korea', ''],
      'Republic of Moldova' => ['Moldova', ''],
      'Republic of North Macedonia' => ['North Macedonia', 'MKD'],
      'Republic of the Congo' => ['Congo', ''],
      'Reunion' => ['Reunion', 'REU'],
      'Réunion' => ['Reunion', 'REU'],
      'Romania' => ['Romania', 'ROU'],
      'Russia' => ['Russia', 'RUS'],
      'Russian Federation (the)' => ['Russia', 'RUS'],
      'Russian Federation' => ['Russia', ''],
      'Rwanda' => ['Rwanda', 'RWA'],
      'Saint Barthelemy' => ['Saint Barthelemy', ''],
      'Saint Barthélemy' => ['Saint Barthelemy', 'BLM'],
      'Saint Helena, Ascension and Tristan da Cunha' => ['Saint Helena, Ascension and Tristan da Cunha', 'SHN'],
      'Saint Kitts and Nevis' => ['Saint Kitts and Nevis', 'KNA'],
      'Saint Lucia' => ['Saint Lucia', 'LCA'],
      'Saint Martin (French part)' => ['Saint Martin', 'MAF'],
      'Saint Martin' => ['Saint Martin', ''],
      'Saint Pierre and Miquelon' => ['Saint Pierre and Miquelon', 'SPM'],
      'Saint Vincent and the Grenadines' => ['Saint Vincent and the Grenadines', 'VCT'],
      'Samoa' => ['Samoa', 'WSM'],
      'San Marino' => ['San Marino', 'SMR'],
      'Sao Tome and Principe' => ['Sao Tome and Principe', 'STP'],
      'Saudi Arabia' => ['Saudi Arabia', 'SAU'],
      'Senegal' => ['Senegal', 'SEN'],
      'Serbia' => ['Serbia', 'SRB'],
      'Seychelles' => ['Seychelles', 'SYC'],
      'Sierra Leone' => ['Sierra Leone', 'SLE'],
      'Singapore' => ['Singapore', 'SGP'],
      'Sint Maarten (Dutch part)' => ['Sint Maarten', 'SXM'],
      'Slovakia' => ['Slovakia', 'SVK'],
      'Slovenia' => ['Slovenia', 'SVN'],
      'Solomon Islands' => ['Solomon Islands', 'SLB'],
      'Somalia' => ['Somalia', 'SOM'],
      'South Africa' => ['South Africa', 'ZAF'],
      'South Georgia and the South Sandwich Islands' => ['South Georgia and the South Sandwich Islands', 'SGS'],
      'South Sudan' => ['South Sudan', 'SSD'],
      'Spain' => ['Spain', 'ESP'],
      'Sri Lanka' => ['Sri Lanka', 'LKA'],
      'St. Martin' => ['Saint Martin', ''],
      'Sudan (the)' => ['Sudan', 'SDN'],
      'Sudan' => ['Sudan', ''],
      'Suriname' => ['Suriname', 'SUR'],
      'Svalbard and Jan Mayen' => ['Svalbard and Jan Mayen', 'SJM'],
      'Sweden' => ['Sweden', 'SWE'],
      'Switzerland' => ['Switzerland', 'CHE'],
      'Syria' => ['Syria', ''],
      'Syrian Arab Republic' => ['Syrian Arab Republic', 'SYR'],
      'Taipei and environs' => ['Taipei', ''],
      'Taiwan (Province of China)' => ['Taiwan (Province of China)', 'TWN'],
      'Taiwan' => ['Taiwan', 'TWN'],
      'Taiwan*' => ['Taiwan', ''],
      'Tajikistan' => ['Tajikistan', 'TJK'],
      'Tanzania, United Republic of' => ['Tanzania', 'TZA'],
      'Tanzania' => ['Tanzania', ''],
      'Thailand' => ['Thailand', 'THA'],
      'The Bahamas' => ['Bahamas', ''],
      'The Gambia' => ['Gambia', ''],
      'Timor-Leste' => ['Timor-Leste', 'TLS'],
      'Togo' => ['Togo', 'TGO'],
      'Tokelau' => ['Tokelau', 'TKL'],
      'Tonga' => ['Tonga', 'TON'],
      'Trinidad and Tobago' => ['Trinidad and Tobago', 'TTO'],
      'Tunisia' => ['Tunisia', 'TUN'],
      'Turkey' => ['Turkey', 'TUR'],
      'Turkmenistan' => ['Turkmenistan', 'TKM'],
      'Turks and Caicos Islands (the)' => ['Turks and Caicos Islands', 'TCA'],
      'Tuvalu' => ['Tuvalu', 'TUV'],
      'Uganda' => ['Uganda', 'UGA'],
      'Ukraine' => ['Ukraine', 'UKR'],
      'United Arab Emirates (the)' => ['United Arab Emirates', 'ARE'],
      'United Arab Emirates' => ['United Arab Emirates', 'ARE'],
      'United Kingdom of Great Britain and Northern Ireland (the)' => ['United Kingdom', 'GBR'],
      'United States Minor Outlying Islands (the)' => ['United States Minor Outlying Islands', 'UMI'],
      'United States of America (the)' => ['United States', 'USA'],
      'Uruguay' => ['Uruguay', 'URY'],
      'Uzbekistan' => ['Uzbekistan', 'UZB'],
      'Vanuatu' => ['Vanuatu', 'VUT'],
      'Vatican City' => ['Vatican', ''],
      'Venezuela (Bolivarian Republic of)' => ['Venezuela', 'VEN'],
      'Venezuela' => ['Venezuela', ''],
      'Viet Nam' => ['Vietnam', 'VNM'],
      'Vietnam' => ['Vietnam', 'VNM'],
      'Virgin Islands (British)' => ['Virgin Islands', 'VI_'],
      'Virgin Islands (U.S.)' => ['Virgin Islands', 'VI_'],
      'Wallis and Futuna' => ['Wallis and Futuna', 'WLF'],
      'West Bank and Gaza' => ['Israel', ''],
      'Western Sahara' => ['Western Sahara', 'ESH'],
      'Yemen' => ['Yemen', 'YEM'],
      'Zambia' => ['Zambia', 'ZMB'],
      'Zimbabwe' => ['Zimbabwe', 'ZWE'],
      'Iran' => ['Iran', 'IRN'],
    }[country.strip] || puts(country) #raise(Exception, "Failed to find #{country}")
  end

  def country_population(country)
    {
      :'Afghanistan' => 38041754,
      :'Albania' => 2880917,
      :'Algeria' => 43053054,
      :'American Samoa' => 55312,
      :'Andorra' => 77142,
      :'Angola' => 31825295,
      :'Anguilla' => 14869,
      :'Antigua and Barbuda' => 97118,
      :'Argentina' => 44780677,
      :'Armenia' => 2957731,
      :'Aruba' => 106314,
      :'Australia' => 25203198,
      :'Austria' => 8955102,
      :'Azerbaijan' => 10047718,
      :'Bahamas' => 389482,
      :'Bahrain' => 1641172,
      :'Bangladesh' => 163046161,
      :'Barbados' => 287025,
      :'Belarus' => 9452411,
      :'Belgium' => 11539328,
      :'Belize' => 390353,
      :'Benin' => 11801151,
      :'Bermuda' => 62506,
      :'Bhutan' => 763092,
      :'Bolivia' => 11513100,
      :'Bosnia and Herzegovina' => 3301000,
      :'Botswana' => 2303697,
      :'Brazil' => 211049527,
      :'British Virgin Islands' => 30030,
      :'Brunei' => 433285,
      :'Bulgaria' => 7000119,
      :'Burkina Faso' => 20321378,
      :'Burundi' => 10864245,
      :'Cambodia' => 16486542,
      :'Cameroon' => 25876380,
      :'Canada' => 37411047,
      :'Cape Verde' => 549935,
      :'Caribbean Netherlands' => 25979,
      :'Cayman Islands' => 64948,
      :'Central African Republic' => 4745185,
      :'Chad' => 15946876,
      :'Chile' => 18952038,
      :'China' => 1433783686,
      :'Colombia' => 50339443,
      :'Comoros' => 850886,
      :'Congo' => 5380508,
      :'Cook Islands' => 17548,
      :'Costa Rica' => 5047561,
      :'Croatia' => 4130304,
      :'Cuba' => 11333483,
      :'Curaçao' => 163424,
      :'Cyprus' => 1179551,
      :'Czech Republic' => 10689209,
      :'Denmark' => 5771876,
      :'Djibouti' => 973560,
      :'Dominica' => 71808,
      :'Dominican Republic' => 10738958,
      :'DR Congo' => 86790567,
      :'East Timor' => 1293119,
      :'Ecuador' => 17373662,
      :'Egypt' => 100388073,
      :'El Salvador' => 6453553,
      :'Equatorial Guinea' => 1355986,
      :'Eritrea' => 3497117,
      :'Estonia' => 1325648,
      :'Eswatini' => 1148130,
      :'Ethiopia' => 112078730,
      :'F.S. Micronesia' => 113815,
      :'Falkland Islands' => 3377,
      :'Faroe Islands' => 48678,
      :'Fiji' => 889953,
      :'Finland' => 5532156,
      :'France' => 65129728,
      :'French Guiana' => 282731,
      :'French Polynesia' => 279287,
      :'Gabon' => 2172579,
      :'Gambia' => 2347706,
      :'Georgia' => 3996765,
      :'Germany' => 83517045,
      :'Ghana' => 28833629,
      :'Gibraltar' => 33701,
      :'United Kingdom' => 67530172,
      :'Greece' => 10473455,
      :'Greenland' => 56672,
      :'Grenada' => 112003,
      :'Guadeloupe' => 447905,
      :'Guam' => 167294,
      :'Guatemala' => 17581472,
      :'Guernsey and  Jersey' => 172259,
      :'Guinea' => 12771246,
      :'Guinea-Bissau' => 1920922,
      :'Guyana' => 782766,
      :'Haiti' => 11263770,
      :'Honduras' => 9746117,
      :'Hong Kong' => 7436154,
      :'Hungary' => 9684679,
      :'Iceland' => 339031,
      :'India' => 1366417754,
      :'Indonesia' => 270625568,
      :'Iran' => 82913906,
      :'Iraq' => 39309783,
      :'Ireland' => 4882495,
      :'Isle of Man' => 84584,
      :'Israel' => 8519377,
      :'Italy' => 60550075,
      :'Ivory Coast' => 25716544,
      :'Jamaica' => 2948279,
      :'Japan' => 126860301,
      :'Jordan' => 10101694,
      :'Kazakhstan' => 18551427,
      :'Kenya' => 52573973,
      :'Kiribati' => 117606,
      :'Kuwait' => 4207083,
      :'Kyrgyzstan' => 6415850,
      :'Laos' => 7169455,
      :'Latvia' => 1906743,
      :'Lebanon' => 6855713,
      :'Lesotho' => 2125268,
      :'Liberia' => 4937374,
      :'Libya' => 6777452,
      :'Liechtenstein' => 38019,
      :'Lithuania' => 2759627,
      :'Luxembourg' => 615729,
      :'Macau' => 640445,
      :'Madagascar' => 26969307,
      :'Malawi' => 18628747,
      :'Malaysia' => 31949777,
      :'Maldives' => 530953,
      :'Mali' => 19658031,
      :'Malta' => 440372,
      :'Marshall Islands' => 58791,
      :'Martinique' => 375554,
      :'Mauritania' => 4525696,
      :'Mauritius' => 1198575,
      :'Mayotte' => 266150,
      :'Mexico' => 127575529,
      :'Moldova' => 4043263,
      :'Monaco' => 38964,
      :'Mongolia' => 3225167,
      :'Montenegro' => 627987,
      :'Montserrat' => 4989,
      :'Morocco' => 36471769,
      :'Mozambique' => 30366036,
      :'Myanmar' => 54045420,
      :'Namibia' => 2494530,
      :'Nauru' => 10756,
      :' Nepal' => 28608710,
      :'Netherlands' => 17097130,
      :'New Caledonia' => 282750,
      :'New Zealand' => 4783063,
      :'Nicaragua' => 6545502,
      :'Niger' => 23310715,
      :'Nigeria' => 200963599,
      :'Niue' => 1615,
      :'North Korea' => 25666161,
      :'North Macedonia' => 2083459,
      :'Northern Mariana Islands' => 56188,
      :'Norway' => 5378857,
      :'Oman' => 4974986,
      :'Pakistan' => 216565318,
      :'Palau' => 18008,
      :'Palestine' => 4981420,
      :'Panama' => 4246439,
      :'Papua New Guinea' => 8776109,
      :'Paraguay' => 7044636,
      :'Peru' => 32510453,
      :'Philippines' => 108116615,
      :'Poland' => 37887768,
      :'Portugal' => 10226187,
      :'Puerto Rico' => 2933408,
      :'Qatar' => 2832067,
      :'Réunion' => 888927,
      :'Romania' => 19364557,
      :'Russia' => 145872256,
      :'Rwanda' => 12626950,
      :'Saint Helena Ascension and Tristan da Cunha' => 6059,
      :'Saint Kitts and Nevis' => 52823,
      :'Saint Lucia' => 182790,
      :'Saint Pierre and Miquelon' => 5822,
      :'Saint Vincent and the Grenadines' => 110589,
      :'Samoa' => 197097,
      :'San Marino' => 33860,
      :'São Tomé and Príncipe' => 215056,
      :'Saudi Arabia' => 34268528,
      :'Senegal' => 16296364,
      :'Serbia' => 8772235,
      :'Seychelles' => 97739,
      :'Sierra Leone' => 7813215,
      :'Singapore' => 5804337,
      :'Sint Maarten' => 42388,
      :'Slovakia' => 5457013,
      :'Slovenia' => 2078654,
      :'Solomon Islands' => 669823,
      :'Somalia' => 15442905,
      :'South Africa' => 58558270,
      :'South Korea' => 51225308,
      :'South Sudan' => 11062113,
      :'Spain' => 46736776,
      :'Sri Lanka' => 21323733,
      :'Sudan' => 42813238,
      :'Suriname' => 581372,
      :'Sweden' => 10036379,
      :'Switzerland' => 8591365,
      :'Syria' => 17070135,
      :'Taiwan' => 23773876,
      :'Tajikistan' => 9321018,
      :'Tanzania' => 58005463,
      :'Thailand' => 69037513,
      :'Togo' => 8082366,
      :'Tokelau' => 1340,
      :'Tonga' => 110940,
      :'Trinidad and Tobago' => 1394973,
      :'Tunisia' => 11694719,
      :'Turkey' => 83429615,
      :'Turkmenistan' => 5942089,
      :'Turks and Caicos Islands' => 38191,
      :'Tuvalu' => 11646,
      :'U.S. Virgin Islands' => 104578,
      :'Uganda' => 44269594,
      :'Ukraine' => 43993638,
      :'United Arab Emirates' => 9770529,
      :'United States' => 329064917,
      :'Uruguay' => 3461734,
      :'Uzbekistan' => 32981716,
      :'Vanuatu' => 299882,
      :'Vatican' => 799,
      :'Venezuela' => 28515829,
      :'Vietnam' => 96462106,
      :'Wallis and Futuna' => 11432,
      :'Western Sahara' => 582463,
      :'Yemen' => 29161922,
      :'Zambia' => 17861030,
      :'Zimbabwe' => 14645468,

      :'Cruise Ships' => 0,
      :Nepal => 0,
      :'Cabo Verde' => 0,
      :Czechia => 0,
      :'Timor-Leste' => 0,
      :'Saint Barthelemy' => 0,
      :'Saint Martin' => 0,
      :'Channel Islands' => 0,
      :'Reunion' => 0,
      :Kosovo => 0,
      :Burma => 0,
      :Macao => 0,
      :Curacao => 0,
      :Taipei => 0,
    }[country.to_sym] || puts("Unknown country pop: #{country}")
  end

  def country_data(country=nil)
    @county_data ||= cached(@delay) do
      # get the fresh data from the NYT
      unless system('cd ../../COVID-19; git pull >/dev/null')
        puts "Failed to update covid-19-data"
        exit
      end

      ret = {}
      Dir['../../COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/*.csv'].each do |path|
        hdr, *rest = open(path).read.split("\n")
        rest = rest.sort.uniq
        data = [hdr.parse_csv.join("\t")] + rest.map { |r| r.parse_csv.join("\t")}
        data.each_struct("\t") do |record|
          %w[Confirmed Deaths Recovered].map { |k| k.to_sym }.each { |k| record[k] = record[k].to_i}
          record = country_fix_record(record.to_h)
          next if record.nil?
          s1 = ret[record[:country]] ||= {
            code: record[:code],
            name: record[:country],
            type: 'country',

            beds: 0, #us_county_beds(record[:fips])[:beds],
            population: record[:population],
            centroid: [0,0], # country centroid
            dailyData: {}
          }
          # The JH cases and deaths (and recovered, which we do not use)
          r = [record[:cases], 0, 0, 0, record[:deaths], 0]
          r = @date_stat_struct.new(*r).to_h

          # make sure there is something to receive it, and then add this entry in to whatever is already there
          s2 = s1[:dailyData][record[:date]] ||= blank_struct
          r.each { |k,v| s2[k] += v }
        end
      end
      # the international data is pretty crappy compared to the us data, so use that instead
      ret['United States'] = us_state_data[:ALL]
      data_finish(ret)
    end
    return @county_data[country] unless country.nil?
    @county_data
  end
end